-- liquibase formatted sql

-- changeset Danila:1765788199349-1
CREATE TABLE bookings
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    verified_at TIMESTAMP WITHOUT TIME ZONE,
    start_date  date,
    end_date    date,
    item_id     BIGINT,
    booker_id   BIGINT,
    status      VARCHAR(255),
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

-- changeset Danila:1765788199349-2
CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    item_id    BIGINT,
    booking_id BIGINT,
    text       VARCHAR(255),
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

-- changeset Danila:1765788199349-3
CREATE TABLE items
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    status        SMALLINT,
    price_per_day DECIMAL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    owner_id      BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

-- changeset Danila:1765788199349-4
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset Danila:1765788199349-5
CREATE TABLE users_items
(
    user_id  BIGINT NOT NULL,
    items_id BIGINT NOT NULL
);

-- changeset Danila:1765788199349-6
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset Danila:1765788199349-7
ALTER TABLE users_items
    ADD CONSTRAINT uc_users_items_items UNIQUE (items_id);

-- changeset Danila:1765788199349-8
ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_BOOKER FOREIGN KEY (booker_id) REFERENCES users (id);

-- changeset Danila:1765788199349-9
ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);

-- changeset Danila:1765788199349-10
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_BOOKING FOREIGN KEY (booking_id) REFERENCES bookings (id);

-- changeset Danila:1765788199349-11
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);

-- changeset Danila:1765788199349-12
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset Danila:1765788199349-13
ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

-- changeset Danila:1765788199349-14
ALTER TABLE users_items
    ADD CONSTRAINT fk_useite_on_item FOREIGN KEY (items_id) REFERENCES items (id);

-- changeset Danila:1765788199349-15
ALTER TABLE users_items
    ADD CONSTRAINT fk_useite_on_user FOREIGN KEY (user_id) REFERENCES users (id);

